### PR TITLE
Make back/front_fb_data and back/front_fb not accept arguments

### PR DESCRIPTION
**Pull request by fuglaro**
Makes back_fb_data, front_fb_data, back_fb and front_fb not accept arguments, and instead documents their returned values' mutability.
This feature was not yet implemented and would likely be superfluous.
Mutating the returned values is sufficient so there isn't a benefit to implement accepting arguments for setting.
The outcome is a simpler and clearer API, simpler code, and one less branch condition at runtime.

### CODE REVIEW

**Comment by fuglaro** [comment]
I did some basic testing of this to ensure:
- all functions no longer accept arguments and give the corrent exception if given one.
- all returned values can be mutated and manipulated.
- the docs still build correctly.

**Comment by TPReal** [comment]
I'm not sure this is a good change. Setting the whole buffer might theoretically make sense if someone wants to implement their own double buffering, or triple buffering, or very quickly switch between 3 or more frames. The last thing would now require copying data between buffers, while, if the buffer identity could be set by the setter, it would be enough to swap the whole buffers. So removing the possibility of setting the identity seems to remove some possibilities, without very clear benefit (apart from the fact that the setters were not yet implemented...).

**Comment by fuglaro** [comment]
Thanks for taking a look! I presumed that custom double or tripple buffering wouldn't be supported because I thought engine.tick already does the swapping of those buffers. Is that not the case? But if there was a plan to support that, even if that meant changing the behaviour of engine.tick, or providing access to the individual things it does behind the scenes, then yes we lose something here. I didn't think supporting that was just a matter of adding that missing implementation.

If the missing implementation was made, would that really be possible? Or was there a plan to support that?

**Comment by fuglaro** [comment]
I'm not too fussed though. I love complexity economics and this felt like a win here. But I'm very happy to cancel this PR if it just feels a bit wonky.

**Comment by fuglaro** [comment]
I dug a little and it looks like engine_tick swaps the underlying c arrays from inside the front_fb_data() bytearray object and the back one. If we tried to use the set functionality in the cases listed above, I think it will end up doing some weird things to and bytearray or framebuf objects used as the passed in "set" parameters. Without wider changes to the way the engine swaps framebufs, the missing implementation would have to do a copy to avoid messing with the passed in buffers.

**Comment by TPReal** [comment]
Well, you're right that this makes things even more complicated and probably not practical. So in the current state keeping the setters makes little sense.

**Comment by TinyCircuits** [comment]
Sorry about the conflict. I had to fix the back/front buffer order. I still think it makes sense to get rid of the setter mentions (for now). I think the only conflicts you should get are my comments. Can you add something about the fact that the front buffer is being sent to the screen and that the back buffer is the one to draw to?

I know the explanation about the front buffer being the one sent to the screen is a little verbose, but I like to give people reasons for why they should and shouldn't do things.

**Comment by fuglaro** [comment]
Thank you! I'm very happy to add that and resolve that conflict, and will try to do that soon. I saw the change with the buffer order and that is brilliant. Nice catch.

**Pull request merged**
